version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/zcloud-ws/secure-templates/pkg/app.appVersion={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

release:
  github:
    owner: zcloud-ws
    name: secure-templates
  draft: false
  prerelease: auto

changelog:
  sort: asc
  abbrev: 7
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
